### ISSUE TITLE
Why the layout?

### ISSUE THREAD

**Issue by KennyGoers** [Flipboard/bottomsheet#9] opened 2015-06-24 23:29 UTC
Why can't you use the BottomSheet as a dialog like class instead of embedding it as part of a layout? If I'm not seeing it. please let me know, but this is far more useful if can use it in that way instead of it having to be put as a wrapper in every layout.

Thanks, I like the features, but don't see why it needs to be done in this fashion.

**Comment by hzsweers** [comment] 2015-06-24 23:34
Functionally speaking, how would you propose this be handled as a dialog? It's built this way right now so that you can have the content view interact with its movements accordingly, and it's not much work to stuff this down into a base activity.

**Comment by hzsweers** [comment] 2015-07-01 07:18
Going to close this for now, we can revisit if others have some good suggestions for a dialog approach.

**Closed** 2015-07-01 07:19 UTC

**Comment by schwiz** [comment] 2015-07-24 16:04
Just a thought here, but perhaps bottomsheet could be refactored to use Google's CoordinatorLayout its Behavior implementation for scrolling. Since this library is trying to aid in material design support having the design support lib as a dependency wouldn't be bad I don't think.

**Comment by hzsweers** [comment] 2015-07-24 16:18
How would that work implementation-wise? I'm not too familiar with
CoordinatorLayout yet

**Comment by schwiz** [comment] 2015-07-24 16:47
CoordinatorLayout is a ViewGroup that looks at every child's layout params for a [Behavior](https://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.Behavior.html). The Behavior tells the CoordinatorLayout how that childview should interact with other views and handles nested scrolling and other things. 

For example, when you add a FloatingActionButton to a CoordinatorLayout it finds FAB's default Behavior attached and uses it to move the button on the screen based off of its anchor View, or to animate and hide if it gets too close to the Toolbar.

What I'm suggesting for bottomsheet is instead of BottomSheetLayout being a top level view it would be refactored into a view that implements a default Behavior.  That would help avoid nesting so many containers like the pseudo XML below required to support both FAB and Bottomsheet in a single view.

    
    <com.flipboard.bottomsheet.BottomSheetLayout>
           <android.support.design.widget.CoordinatorLayout>
              <!--Toolbar, Content, FAB, etc all goes here.  BottomSheetLayout replacement here as well instead>
           </android.support.design.widget.CoordinatorLayout>
     
    </com.flipboard.bottomsheet.BottomSheetLayout>

**Comment by hzsweers** [comment] 2015-07-24 17:07
Right, I did understand that much. It's behavior implementations themselves
that I'm not too knowledgable on. Are they flexible enough allow for the
same API? Allowing for custom ViewTransformer implementations to interact
with the content view is a must for us.

**Comment by schwiz** [comment] 2015-07-24 17:15
I'm not following you on the requirement for ViewTransformer implementations. But I don't think your API would change at all, only the requirement for a top-level view. But thinking about it I suppose there is no reason your BottomSheetLayout needs to be top level either, I suppose it could still be moved inside the CoordinatorLayout in my example above.  I guess to that point moving to Behavior doesn't really change anything, just a different way of solving the same problem.

**Comment by hzsweers** [comment] 2015-07-25 23:17
This is what I'm referring to

![](https://camo.githubusercontent.com/d81602913dd3f1e40268cbe4dfffa9d9697f58a3/687474703a2f2f692e696d6775722e636f6d2f3265335a686f552e676966)

We have to be able to maintain that level of control for the animation.

I agree though that the simple solution would just be to move it inside of CoordinatorLayout, and probably what I'd rather suggesting for now unless CoordinatorLayout offers us some useful API to improve/simplify this logic.

**Comment by kakai248** [comment] 2016-02-17 17:43
I would like to add something about this. I'm currently using a CoordinatorLayout and an AppBarLayout. I'm using the `app:layout_behavior="@string/appbar_scrolling_view_behavior"` so when I scroll down, the toolbar hides. Using the BottomSheetLayout as root is not an option because then the expanded view would go on top of the toolbar leaving no space for the user to click outside of the BottomSheet (as Google guidelines say). What I did was putting the layout under the AppBarLayout, wrapping the content. This creates another problem.

Let me explain how `app:layout_behavior="@string/appbar_scrolling_view_behavior"` works. When you scroll down, the toolbar goes up as well as the childs that use this behavior. When you scroll up, the toolbar comes down and those childs also come down (going offscreen or under the Android virtual buttons). With this behavior the contents height ignores the toolbar height because it will be moved up when the toolbar hides.

The problem is that going offscreen means that the last element present on the BottomSheet list is going to be hidden. I couldn't find a decent solution for this yet. What I'm currently doing is adding an empty MenuItem so it pulls the real items up. And then on the onClickListener I ignore that empty item.

**Comment by hzsweers** [comment] 2016-02-18 03:48
I don't have much experience with CoordinatorLayout but could you not just
place the BottomSheetLayout in the root view of your content?

Also I think your comment about the design guidelines is incorrect. Google
has plenty of examples of full screen bottom sheets covering the whole
view. It's intuitive enough that users know they can drag or press back to
dismiss it. If you really must leave space above, you can set a custom peek
height or use LayoutParams to set your desired expanded height.

Code samples would really help here if you have one.

**Comment by meierjan** [comment] 2016-04-15 14:40
Wouldn't `NestedScrollLayout` be a better choice?
