### ISSUE TITLE
How to custom text colors of each item

### ISSUE THREAD

**Issue by Logan676** [Flipboard/bottomsheet#112] opened 2016-01-04 08:34 UTC
I wonder how to custom its style? I need to change the text color of each item a little bit darker.

**Comment by hzsweers** [comment] 2016-01-04 11:52
You need to be more specific. What items? What style?

**Comment by Logan676** [comment] 2016-01-05 01:46
![device-2016-01-05-0939553](https://cloud.githubusercontent.com/assets/2975850/12105535/b04774ae-b390-11e5-9c0e-25b67a807798.png)
see the screenshot above. 
I am using appcompat-v7, maybe I can change the item text color by adding a new theme in styles.xml, but I don\`t know how, especially when it has to be consistent for all API levels (2.2+) devices.

**Comment by hzsweers** [comment] 2016-01-05 14:07
Ah, this is a dupe of #39 then. We plan to add support at some point, but there's no way to currently.

**Closed** 2016-01-05 14:07 UTC
